services:
  question-gen:
    container_name: QuestionGen
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://compexe_admin:QuiZA.0310!@my-postgres:5432/artilaries
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./log_json_files:/app/log_json_files
    depends_on:
      - my-postgres

  my-postgres:
    image: postgres:15
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: compexe_admin
      POSTGRES_PASSWORD: QuiZA.0310!
      POSTGRES_DB: artilaries
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
