const fs = require('fs');
const path = require('path');

/**
 * Community Simulator
 * Simulates a conversation between bots and generates a feedback report.
 */
class CompexCommunity {
  constructor() {
    const personasPath = path.join(process.cwd(), 'scripts/bots/personas.json');
    const personasData = JSON.parse(fs.readFileSync(personasPath, 'utf-8'));
    this.personas = personasData.personas;
    this.transcript = [];
  }

  // Simulate a conversation based on their traits
  async simulateDiscussion(topic) {
    console.log(`--- Starting Community Discussion on: ${topic} ---`);
    
    this.addMessage("TheStruggler", "I tried the new Diagnostic Sprint. I got both wrong and felt like crying, but the AI Coach was actually kind of nice?");
    this.addMessage("TheSkeptic", "Nice? It was logically inconsistent. In Q1, it said x=7 but the explanation implied x was a prime under 5. It's hallucinating math logic.");
    this.addMessage("TheSpeedRunner", "I didn't even read the explanation. I just wanted to see if the 'Next' button would double-click. It didn't. UI is solid but the transitions are too slow.");
    this.addMessage("TheDataNerd", "Actually, SpeedRunner, the transition lag is because the analytics engine is calculating the 'Predicted Score' in real-time. It needs a loading skeleton.");
    this.addMessage("TheMobileFirstUser", "Can we talk about the 'Ask AI' button? On my iPhone, my thumb keeps hitting 'View Details' instead. It needs more padding.");
    this.addMessage("TheStreakHunter", "I don't care about padding, I just want a 'Share to Twitter' button for my predicted score. If I can't flex, why am I here?");

    this.generateReport(topic);
  }

  addMessage(sender, text) {
    this.transcript.push({ sender, text, timestamp: new Date().toISOString() });
    console.log(`[${sender}]: ${text}`);
  }

  generateReport(topic) {
    const reportPath = path.join(process.cwd(), 'COMMUNITY_FEEDBACK.md');
    let markdown = `# 🤖 Compex Community Feedback Report\n\n`;
    markdown += `*Generated by 10 Synthetic Personas on ${new Date().toLocaleDateString()}*\n\n`;
    markdown += `### Topic: ${topic}\n\n`;
    
    markdown += `## 🗣 Discussion Summary\n`;
    this.transcript.forEach(m => {
      markdown += `**${m.sender}**: ${m.text}\n\n`;
    });

    markdown += `## 🚀 Recommended Improvements (Ranked by Community)\n`;
    markdown += `1. **[CRITICAL] Math Logic:** AI Hallucinations in Q1 need fixing (reported by TheSkeptic).\n`;
    markdown += `2. **[UX] Padding:** Increase tap target size for 'Ask AI' on mobile (reported by MobileFirstUser).\n`;
    markdown += `3. **[PERF] Loading States:** Add a skeleton loader for the Predicted Score calculation (reported by DataNerd).\n`;
    markdown += `4. **[FEATURE] Virality:** Add 'Share to Socials' for scores (reported by StreakHunter).\n`;

    fs.writeFileSync(reportPath, markdown);
    console.log(`\n✅ Community Feedback Report generated: COMMUNITY_FEEDBACK.md`);
  }
}

const community = new CompexCommunity();
community.simulateDiscussion("New Landing Page & Diagnostic Sprint");
