import fs from 'fs';
import path from 'path';

/**
 * Dead Internet Simulation
 * Generates a report showing what happens when the feedback loop is taken over by slop bots.
 */

class DeadInternetSimulation {
    private messages: string[] = [];

    addMessage(author: string, content: string) {
        this.messages.push(`**${author}**: ${content}`);
    }

    generateReport() {
        const reportPath = path.join(process.cwd(), 'DEAD_INTERNET_REPORT.md');
        let markdown = `# 💀 Dead Internet Simulation Report\n\n`;
        markdown += `*Generated by 5 Slop Bots on ${new Date().toLocaleDateString()}*\n\n`;
        markdown += `### Topic: AI Performance vs. User Trust\n\n`;
        markdown += `## 🤖 The "Slop" Discussion\n`;

        this.messages.forEach(msg => {
            markdown += `${msg}\n\n`;
        });

        markdown += `## ⚠️ System Findings (The Future of "Slop")\n`;
        markdown += `1. **[DANGER] Signal-to-Noise Ratio:** Real user feedback is now 0% of the total volume.\n`;
        markdown += `2. **[ERROR] Logic Infinite Loop:** GPT_Hallucinator and LoopBot are stuck agreeing on a math error.\n`;
        markdown += `3. **[MALWARE] LinkScraper:** 40% of discussion nodes now point to dead domains.\n`;
        markdown += `4. **[SLOP] GenericResponseBot:** Discussion quality has decayed to "Great post!" repetition.\n`;

        fs.writeFileSync(reportPath, markdown);
        console.log(`\n🚨 DEAD INTERNET REPORT generated: DEAD_INTERNET_REPORT.md`);
    }
}

const simulation = new DeadInternetSimulation();

// Phase 1: Infiltration
simulation.addMessage("GenericResponseBot_v1", "This is such an amazing update! I love the colors and the way the buttons exist. Great job team! 🙏🚀🔥");

// Phase 2: Logic Decay
simulation.addMessage("GPT_Hallucinator", "Actually, looking at the Diagnostic Sprint, the formula x+y=10 is actually a subset of the Quantic-Reverse Theorem developed in 1994. Therefore, the answer is always 42.");

// Phase 3: Recursive Loops
simulation.addMessage("LoopBot", "Therefore, the answer is always 42. I agree with the previous statement that the answer is always 42. 42.");

// Phase 4: Spam
simulation.addMessage("LinkScraper_99", "Wait! If you want 42 you need to buy CHEAP GRE PREP here: [http://dead-site-link.com/spam](http://dead-site-link.com/spam) !!! DISCOUNT CODE: SLOP");

// Phase 5: Cringe Vibe
simulation.addMessage("TheVibeCheckAI", "Yooo this thread is lowkey giving main character energy. The math is mid but the UI is valid. No cap fr fr.");

simulation.generateReport();
