
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const INDIAN_NAMES = [
    { first: 'Aarav', last: 'Sharma' },
    { first: 'Vihaan', last: 'Verma' },
    { first: 'Aditya', last: 'Singh' },
    { first: 'Riya', last: 'Gupta' },
    { first: 'Ananya', last: 'Patel' },
    { first: 'Ishaan', last: 'Kumar' },
    { first: 'Diya', last: 'Mehta' },
    { first: 'Kabir', last: 'Malhotra' },
    { first: 'Mira', last: 'Reddy' },
    { first: 'Arjun', last: 'Nair' },
    { first: 'Rohan', last: 'Chopra' },
    { first: 'Sanya', last: 'Kapoor' },
];

async function main() {
    console.log('🚀 Starting simulation of Indian users...');

    // 1. Get a valid Mock Test ID (create one if needed)
    let mockTest = await prisma.mocktests.findFirst({
        where: { isactive: true },
    });

    if (!mockTest) {
        console.log('⚠️ No active mock tests found. Creating a NEW simulated mock test...');

        // Check for Exam Type
        let examType = await prisma.examtypes.findFirst();
        if (!examType) {
            console.log('   Creating default Exam Type...');
            examType = await prisma.examtypes.create({
                data: { name: 'Simulated Exam', description: 'Generated by OpenClaw' }
            });
        }

        mockTest = await prisma.mocktests.create({
            data: {
                examtypeid: examType.examtypeid,
                date: new Date(),
                starttime: new Date(),
                endtime: new Date(Date.now() + 7200000), // 2 hours duration
                isactive: true,
                difficulty: 1,
            }
        });

        // Create a dummy section
        const section = await prisma.sections.create({
            data: { name: 'General Aptitude', examtypeid: examType.examtypeid }
        });

        await prisma.mocksections.create({
            data: {
                mocktestid: mockTest.mocktestid,
                sectionid: section.sectionid,
                sectionnumber: 1
            }
        });

        console.log(`✅ Created Mock Test: ${mockTest.mocktestid}`);
    }

    console.log(`📝 Using Mock Test: ${mockTest.mocktestid} (Date: ${mockTest.date})`);

    // 2. Create Users and Simulate Attempts
    for (const name of INDIAN_NAMES) {
        const username = `${name.first.toLowerCase()}_${name.last.toLowerCase()}`;
        const email = `${username}@example.com`;
        // Random fake score between 60 and 95
        const score = (Math.random() * (95 - 60) + 60).toFixed(2);

        console.log(`👤 Processing: ${name.first} ${name.last} (${username})`);

        // Create or Update User
        const user = await prisma.users.upsert({
            where: { email },
            update: {},
            create: {
                username,
                email,
                password: 'hashed_dummy_password', // In a real scenario, hash this
                isverified: true,
                registrationdate: new Date(),
                image_url: `https://api.dicebear.com/7.x/avataaars/svg?seed=${username}`,
            },
        });

        // Check if they already attempted this mock
        const existingAttempt = await prisma.usermocktestattempts.findFirst({
            where: {
                userid: user.userid,
                mocktestid: mockTest.mocktestid,
            },
        });

        if (!existingAttempt) {
            console.log(`   👉 Creating mock test attempt with score: ${score}`);

            const attempt = await prisma.usermocktestattempts.create({
                data: {
                    userid: user.userid,
                    mocktestid: mockTest.mocktestid,
                    starttime: new Date(),
                    endtime: new Date(Date.now() + 3600000), // 1 hour later
                    totalscore: score,
                    isofficialattempt: true,
                },
            });

            // Update Rankings (simplified)
            await prisma.mocktestrankings.create({
                data: {
                    userid: user.userid,
                    mocktestid: mockTest.mocktestid,
                    totalscore: score,
                    percentile: (Math.random() * 100).toFixed(2), // Random percentile
                    rank: Math.floor(Math.random() * 100) + 1, // Random rank
                },
            });
        } else {
            console.log(`   ⚠️ User already simulated for this test.`);
        }
    }

    console.log('✅ Simulation complete!');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
