// Simple Landing Page Component
// Place in: app/page.tsx (or create new landing page)

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      {/* Hero Section */}
      <header className="container mx-auto px-4 py-20 text-center">
        <h1 className="text-5xl font-bold text-gray-900 mb-6">
          Master Any Exam with <span className="text-blue-600">AI-Powered</span> Practice
        </h1>
        <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
          Unlimited personalized practice questions for GRE, GMAT, and more. 
          Generated by AI, refined by real user feedback.
        </p>
        <div className="flex justify-center gap-4">
          <a 
            href="/app"
            className="bg-blue-600 text-white px-8 py-3 rounded-lg font-semibold hover:bg-blue-700 transition"
          >
            Start Free Practice
          </a>
          <a 
            href="#pricing"
            className="border border-gray-300 px-8 py-3 rounded-lg font-semibold hover:bg-gray-50 transition"
          >
            View Pricing
          </a>
        </div>
      </header>

      {/* Stats */}
      <section className="bg-blue-600 text-white py-12">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-3 gap-8 text-center">
            <div>
              <div className="text-4xl font-bold">500+</div>
              <div className="text-blue-200">Practice Questions</div>
            </div>
            <div>
              <div className="text-4xl font-bold">50+</div>
              <div className="text-blue-200">Topics Covered</div>
            </div>
            <div>
              <div className="text-4xl font-bold">95%</div>
              <div className="text-blue-200">User Satisfaction</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">Why Compex?</h2>
          <div className="grid md:grid-cols-3 gap-8">
            <FeatureCard 
              icon="🤖"
              title="AI-Generated"
              description="Unlimited fresh questions powered by Antigravity AI"
            />
            <FeatureCard 
              icon="📊"
              title="Smart Distribution"
              description="Balanced mix of difficulty levels and question types"
            />
            <FeatureCard 
              icon="⭐"
              title="Quality Feedback"
              description="Users rate questions, low-rated ones get regenerated"
            />
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-20 bg-gray-50">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">Simple Pricing</h2>
          <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            <PricingCard 
              name="Free"
              price="$0"
              features={["10 questions/day", "Basic analytics", "Community support"]}
            />
            <PricingCard 
              name="Pro"
              price="$9.99"
              popular
              features={["Unlimited questions", "Detailed analytics", "Priority support", "Mock papers"]}
            />
            <PricingCard 
              name="Team"
              price="$29.99"
              features={["5 team members", "Shared progress", "Admin dashboard", "API access"]}
            />
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-6">Ready to Master Your Exam?</h2>
          <p className="text-gray-600 mb-8">Join thousands of students improving their scores</p>
          <a 
            href="/app"
            className="bg-blue-600 text-white px-8 py-3 rounded-lg font-semibold hover:bg-blue-700 transition"
          >
            Start Free Now
          </a>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-8">
        <div className="container mx-auto px-4 text-center">
          <p>© 2026 Compex. All rights reserved.</p>
          <p className="text-gray-400 text-sm mt-2">AI-Powered Practice Platform</p>
        </div>
      </footer>
    </div>
  );
}

function FeatureCard({ icon, title, description }: { icon: string; title: string; description: string }) {
  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
      <div className="text-4xl mb-4">{icon}</div>
      <h3 className="text-xl font-semibold mb-2">{title}</h3>
      <p className="text-gray-600">{description}</p>
    </div>
  );
}

function PricingCard({ name, price, features, popular }: { name: string; price: string; features: string[]; popular?: boolean }) {
  return (
    <div className={`p-8 rounded-xl ${popular ? 'bg-blue-600 text-white' : 'bg-white border border-gray-200'}`}>
      <h3 className="text-xl font-semibold mb-2">{name}</h3>
      <div className="text-4xl font-bold mb-6">{price}<span className="text-sm font-normal">/mo</span></div>
      <ul className="space-y-3 mb-8">
        {features.map((f, i) => (
          <li key={i} className="flex items-center gap-2">
            <span className="text-green-500">✓</span>
            {f}
          </li>
        ))}
      </ul>
      <button className={`w-full py-3 rounded-lg font-semibold transition ${
        popular ? 'bg-white text-blue-600 hover:bg-gray-100' : 'bg-blue-600 text-white hover:bg-blue-700'
      }`}>
        Get Started
      </button>
    </div>
  );
}
