[Interface]
PrivateKey = 0N4Wv2FSfn/JUs8JWZbp0pTdqq8fjTUKC3lvCFjYl1E=
Address = 10.100.0.2/32
DNS = 8.8.8.8

[Peer]
PublicKey = DkPEz0M0J08HxjhtaV5e3et+c1GDkGnQfXsXlXiLwR0=
Endpoint = 65.20.79.187:51820
AllowedIPs = 10.100.0.0/24
PersistentKeepalive = 25
